server:
  port: 8083
logging:
  level:
    root: DEBUG
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "authentication_db"
    schema: "public"
    username: "postgres"
    password: "root"

